from airflow.sdk import dag, Asset, task
from pendulum import datetime

# The URI generated by Cosmos in Airflow 3 uses slashes
# This asset represents the 'customers' table in the public schema
my_asset = Asset("postgres://postgres:5432/postgres/public/customers")

@dag(
    schedule=[my_asset],  # This DAG triggers automatically when the dbt model is updated
    start_date=datetime(2025, 1, 1),
    catchup=False
)
def downstream_asset_check():
    @task
    def print_msg():
        # Translated print message for the team
        print("The dbt Asset is ready, I can now launch the downstream process!")
    
    print_msg()

downstream_asset_check()